### ISSUE TITLE
Join forces

### ISSUE THREAD

**Issue by alexanderadam** [russ/eighttrack#1]
Hey Russ,

did you see [hi8.cr](https://github.com/vonKingsley/hi8.cr)?
If not you may have a look on it and maybe help over there.

Otherwise: do you have any particular plans what should be different from hi8?

**Comment by russ** [comment]
Haha, well I guess I didn't do enough searching when I needed a solution. Looks like that one is quite a bit more complete than mine. I don't have plans to take this project any further really. Matter of fact, if this doesn't work out at any point I'll be switching over and making updates if needed.

**Comment by alexanderadam** [comment]
Awesome, it's not "my" project but as I am a hi8.cr user I'm happy for everyone who says he considers a contribution. :+1: 

Have a wonderful day!
